/* autogenerated by Processing revision 1293 on 2024-08-20 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.awt.Desktop;
import java.net.URI;
import java.io.IOException;
import java.net.URISyntaxException;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class ConsoleEmulator extends PApplet {






Desktop desktop = Desktop.getDesktop();

final int SCENE_HOME = 0;
final int SCENE_THEME = 1;
final int SCENE_LANGUAGE = 2;
final int SCENE_PROJECT_SELECT = 3;
final int SCENE_SETTINGS = 4;
final int SCENE_INTRO_PREQUEL = 5;
final int SCENE_INTRO_TUTORIAL = 6;
int scene = SCENE_HOME;

boolean showTutorial;

PImage consoleEmulatorLogo;

boolean isMouseReleased = false;
int mouseReleasedX;
int mouseReleasedY;


JSONObject coreConfig;
JSONObject saveFile;


UIButton themeMenuBack;
UIButton settingsMenuBack;
UIButton languageMenuBack;
UIButton homeMenuExit;
UIButton settingsMenuTheme;
UIButton settingsMenuFactoryReset;
UIButton settingsMenuLanguage;
UIButton homeMenuEditor;
UIButton homeMenuProject;
UIButton homeMenuSettings;
UIButton projectMenuBack;
UIButton homeMenuDocumentation;
UIButton introMenuNext;


public void setup(){
  
  coreConfig = loadJSONObject("internal/core.json");
  saveFile = loadJSONObject("internal/save.json");
  
  loadDataFromSave();
  
  PImage icon = loadImage(coreConfig.getString("iconFilepath"));
  surface.setIcon(icon);
  surface.setTitle("ConsoleEmulator " + coreConfig.getString("versionString") + "    |    DIY Labs 2024");
  
  
  if(coreConfig == null){
   super.exit(); 
  }
  
  consoleEmulatorLogo = loadImage(coreConfig.getString("logoFilepath"));
  consoleEmulatorLogo.resize(900, 0);
  
  if(!localisationInit()){
    exit();
  }

  if(!themeInit()){
    exit();
  }
    
  loadUIElements();
  
  /* size commented out by preprocessor */;
    
}

public void draw(){
   
  background(THEME_BACKGROUND_COL);
  
  switch(scene){
   
    case SCENE_HOME:
      homePage();
    break;
    
    case SCENE_THEME:
      themeSelector();
    break;
    
    case SCENE_LANGUAGE:
      languageSelector();
    break;
    
    case SCENE_PROJECT_SELECT:
      projectSelector();
    break;
    
    case SCENE_SETTINGS:
      settingsPage();
    break;
      
    case SCENE_INTRO_PREQUEL:
      introPrequel();
    break;

    case SCENE_INTRO_TUTORIAL:
      intro();
    break;
      
    default:
      errorPageScene();
    break;
    
  }
  
  
}

public void mouseReleased(){
  
  isMouseReleased = true;
  mouseReleasedX = mouseX;;
  mouseReleasedY = mouseY;
  
}


public void keyReleased(){
   
  if(scene == SCENE_THEME){
      
    if(keyCode == UP){
      
      handleThemeDecrement();
      
    }
    
    if(keyCode == DOWN){
      
      handleThemeIncrement();

    }
    
  }
  
  if(scene == SCENE_LANGUAGE || scene == SCENE_INTRO_PREQUEL){
      
    if(keyCode == UP){
      
      handleLanguageDecrement();
      
    }
    
    if(keyCode == DOWN){
      
      handleLanguageIncrement();

    }
    
  }
  
  if(keyCode == TAB){
   
    frameCount = -1;
    
  }

  if(key == DELETE){
    
    logDebugInfo();
    
  }
  
  if(scene == SCENE_INTRO_TUTORIAL){
   
    scene = SCENE_HOME;
    
  }

}

public void loadUIElements(){
  
  int y = 120;
  int inc = 55;

  themeMenuBack            = new UIButton(140, 30, 5, 5, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_BACK"));
  languageMenuBack         = new UIButton(140, 30, 5, 5, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_BACK"));
  projectMenuBack          = new UIButton(140, 30, 5, 5, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_BACK"));
  settingsMenuBack         = new UIButton(140, 30, 5, 5, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_BACK"));

  homeMenuEditor           = new UIButton(350, 45, UI_BUTTON_CENTER, y, 2, THEME_BACKGROUND_COL, THEME_BACKGROUND_COL, THEME_UNAVAILABLE_COL, THEME_UNAVAILABLE_COL, THEME_UNAVAILABLE_COL, THEME_UNAVAILABLE_COL, localisation.getString("UI_BUTTON_EDITOR"));
  y += inc;
  homeMenuProject          = new UIButton(350, 45, UI_BUTTON_CENTER, y, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_PROJECTS"));
  y += inc;
  homeMenuDocumentation    = new UIButton(350, 45, UI_BUTTON_CENTER, y, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_DOCUMENTATION"));
  homeMenuSettings         = new UIButton(350, 45, UI_BUTTON_CENTER, 325, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_SETTINGS"));  
  homeMenuExit             = new UIButton(350, 45, UI_BUTTON_CENTER, height - 80, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_EXIT"));
  
  y = 100;
  inc = 55;

  settingsMenuTheme        = new UIButton(350, 45, UI_BUTTON_CENTER, y, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_THEMES"));
  y += inc;
  settingsMenuLanguage     = new UIButton(350, 45, UI_BUTTON_CENTER, y, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_LANGUAGES"));

  settingsMenuFactoryReset = new UIButton(350, 30, UI_BUTTON_CENTER, height - 35, 2, THEME_BACKGROUND_COL, THEME_ERROR_MAJOR_COL, THEME_ERROR_MAJOR_COL, THEME_ERROR_MAJOR_COL, THEME_ERROR_MAJOR_COL, THEME_ERROR_MAJOR_COL, localisation.getString("UI_BUTTON_FACRESET"));

  introMenuNext            = new UIButton(350, 45, UI_BUTTON_CENTER, height - 80, 2, THEME_BACKGROUND_COL, THEME_HIGHLIGHT_COL, THEME_HIGHLIGHT_COL, THEME_FOREGROUND_COL, THEME_FOREGROUND_COL, THEME_BACKGROUND_COL, localisation.getString("UI_BUTTON_NEXT"));
 

}

public void errorPageScene(){
 
  fill(255, 0, 0);
  strokeWeight(0);
  background(0);
  
  textAlign(CENTER, CENTER);
  textSize(50);
  
  text(localisation.getString("UI_SCENE_ILLEGAL"), width/2, height/2);
  
}

public void homePage(){
 
  if(homeMenuExit.handle()){
    safeExit();   
  }
     
  if(homeMenuProject.handle()){
   scene = SCENE_PROJECT_SELECT; 
  }
  
  if(homeMenuDocumentation.handle()){
   openWebPage("https://github.com/DIYLabsED/ConsoleEmulator/wiki"); 
  }

  if(homeMenuSettings.handle()){
   scene = SCENE_SETTINGS; 
  }

  homeMenuEditor.handle();
  
  image(consoleEmulatorLogo, 0, 0);
  tint(THEME_HIGHLIGHT_COL);
  
  fill(THEME_FOREGROUND_COL);
  strokeWeight(0);
  textSize(14);
  textAlign(LEFT, BOTTOM);
  text("ConsoleEmulator " + coreConfig.getString("versionString"), 2, height - 2);
  textAlign(RIGHT, BOTTOM);
  text(coreConfig.getString("githubRepo"), width - 2, height - 2);
  
}

public void settingsPage(){
  
  fill(THEME_FOREGROUND_COL);
  strokeWeight(0);
      
  textSize(40);
  textAlign(CENTER, TOP);
  text(localisation.getString("UI_SCENE_SETTINGS"), width/2, 10);
  
  if(settingsMenuBack.handle()){
    scene = SCENE_HOME;   
  }
  if(settingsMenuTheme.handle()){
    scene = SCENE_THEME;  
  }
  
  if(settingsMenuLanguage.handle()){
    scene = SCENE_LANGUAGE;  
  }
  
  if(settingsMenuFactoryReset.handle()){
   
    factoryReset();
    
  }

}

// prevent window from closing when escape key is pressed
// to close sketch, super.exit() is used
public void exit(){
    
}

public void openWebPage(String siteUrl) {
  
  try {
    URI site = new URI(siteUrl);
    if (Desktop.isDesktopSupported() && desktop.isSupported(Desktop.Action.BROWSE)) {
      desktop.browse(site);
    } else {
      println("Desktop does not support browse");
    }
  } catch(URISyntaxException e) {
    e.printStackTrace();
  } catch(IOException e) {
    e.printStackTrace();
  }
  
}

public void loadDataFromSave(){
 
  selectedTheme = saveFile.getInt("theme");  
  selectedLanguage = saveFile.getInt("language");
  showTutorial = saveFile.getBoolean("showTutorial");
  
  if(showTutorial){
   scene = SCENE_INTRO_PREQUEL; 
  }
  
}

public void saveDataToSave(){

  JSONObject temp = new JSONObject();
  
  temp.setInt("theme", selectedTheme);
  temp.setInt("language", selectedLanguage);
  temp.setBoolean("showTutorial", false);
  
  saveJSONObject(temp, coreConfig.getString("saveFileFilePath"));
    
}

public void logDebugInfo(){
  
  // Layout of log:
  // Date | Time (YYYYMMDD | HHMMSS
  // Sketch file path
  // CE Version
  // OS name
  // OS arch
  // Java vendor name
  // Processor identifier
  
  String filePath = sketchPath(coreConfig.getString("mainLogFilePathAppend"));
  String[] log = new String[8];
  
  log[0] = "THIS LOG MAY CONTAIN PERSONAL INFORMATION. DO NOT SHARE IT UNLESS YOU TRUST THE RECIPIENT!\n";
  log[1] = "Date | Time: " + str(year()) + str(month()) + str(day()) + "  |  " + str(hour()) + ":" + str(minute()) + ":" + str(second());
  log[2] = "CE filepath: " + sketchPath();
  log[3] = "CE version: " + coreConfig.getString("versionString");
  log[4] = "OS name: " + System.getProperty("os.name");
  log[5] = "OS architecture: " + System.getProperty("os.arch");
  log[6] = "Java vendor name: " + System.getProperty("java.vendor");
  log[7] = "Processor identifier: " + System.getenv("PROCESSOR_IDENTIFIER");
  
  saveStrings(filePath, log);
  
  background(255);
  
}

public void intro(){
 
  fill(THEME_FOREGROUND_COL);
  strokeWeight(0);
      
  textSize(40);
  textAlign(CENTER, TOP);
  text(localisation.getString("UI_SCENE_INTRO"), width/2, 10);
  
  textSize(25);
  text(localisation.getString("UI_SCENE_INTRO_SUB1"), width/2, 120);
  text(localisation.getString("UI_SCENE_INTRO_SUB2"), width/2, 150);
  
  textSize(20);
  fill(THEME_HIGHLIGHT_COL);
  text(sketchPath(coreConfig.getString("mainLogFilePathAppend")), width/2, 185);  
 
  fill(THEME_FOREGROUND_COL);
  textAlign(CENTER, BOTTOM);
  text(localisation.getString("UI_SCENE_INTRO_SUB3"), width/2, height - 40);
  text(localisation.getString("UI_SCENE_INTRO_SUB4"), width/2, height - 10);
  
}

public void safeExit(){
  
  saveDataToSave();
  super.exit();
  
}

public void factoryReset(){
 
  JSONObject temp = new JSONObject();
  
  temp.setInt("theme", 0);
  temp.setInt("language", 0);
  temp.setBoolean("showTutorial", true);
  
  saveJSONObject(temp, coreConfig.getString("saveFileFilePath"));
  
  super.exit();
  
}
final String LOCALISATION_FILE_FILEPATH = "internal/localisation.json";
JSONObject localisation;
JSONArray languages;

int selectedLanguage = 0;

public boolean localisationInit(){
 
  languages = loadJSONArray(LOCALISATION_FILE_FILEPATH);
  
  if(languages == null){
    
    println("Unable to load loc file");
    return false;
    
  }
  
  loadLanguage(selectedLanguage);
  
  return true;
  
}

public void loadLanguage(int index){
 
  localisation = languages.getJSONObject(index);
  loadUIElements();
  saveDataToSave();
  
}

public void languageSelector(){
  
  if(languageMenuBack.handle()){
   
    scene = SCENE_SETTINGS;
    
  }
  
  fill(THEME_FOREGROUND_COL);
  strokeWeight(0);
      
  textSize(40);
  textAlign(CENTER, TOP);
  text(localisation.getString("UI_SCENE_LANGUAGES"), width/2, 10);

  textSize(18);
  text(localisation.getString("UI_SCENE_LANGUAGES_SUB1"), width/2, 60);
  text(localisation.getString("UI_SCENE_LANGUAGES_SUB2"), width/2, 80);

  
  for(int i = 0; i < languages.size(); i++){

    fill(THEME_FOREGROUND_COL);
    strokeWeight(0);
    
    JSONObject l = languages.getJSONObject(i);
  
    // [id] name    creator
    int textSize = 30;
    int marginX = 20;
    int marginY = 5;
    int initialX = marginX; // topleft
    int initialY = 120;
    int nameX;
    int creatorX = width - marginX; // topright!
    
    float yOffset = initialY + (i * textSize);
    float selectionYOffset = initialY + (selectedLanguage * textSize) - 2;
    
    float selectionYMargin = textDescent() / 3;
    
    textSize(textSize - (textSize  / 5));
    textAlign(LEFT, TOP);
    
    String id = "[" + str(i) + "]";
    int maxIDWidth = PApplet.parseInt(textWidth("[99]"));
    nameX = initialX + maxIDWidth + marginX;
    
    text(id, initialX, yOffset);
    
    text(l.getString("language"), nameX, yOffset);
    
    fill(THEME_FOREGROUND_COL);
    textAlign(RIGHT, TOP);
    text(localisation.getString("UI_SCENE_LANGUAGES_CREATOR_PRETEXT") + l.getString("creator"), creatorX, yOffset);
    
    fill(0, 0, 0, 0);
    stroke(THEME_HIGHLIGHT_COL);
    strokeWeight(1.5f);
    rect(initialX - (marginX/2), selectionYOffset - selectionYMargin, creatorX , textSize - selectionYMargin);
        
  } 

    
}

public void handleLanguageIncrement(){
  
  selectedLanguage = (selectedLanguage + languages.size() + 1) % languages.size();
  loadLanguage(selectedLanguage);
  
}
public void handleLanguageDecrement(){

  selectedLanguage = (selectedLanguage + languages.size() - 1) % languages.size();
  loadLanguage(selectedLanguage);
  
}

public void introPrequel(){
  
  fill(THEME_FOREGROUND_COL);
  strokeWeight(0);
      
  textSize(40);
  textAlign(CENTER, TOP);
  text(localisation.getString("UI_SCENE_LANGUAGES"), width/2, 10);

  textSize(18);
  text(localisation.getString("UI_SCENE_LANGUAGES_SUB1"), width/2, 60);
  text(localisation.getString("UI_SCENE_LANGUAGES_SUB2"), width/2, 80);  
  
  for(int i = 0; i < languages.size(); i++){

    fill(THEME_FOREGROUND_COL);
    strokeWeight(0);
    
    JSONObject l = languages.getJSONObject(i);
  
    // [id] name    creator
    int textSize = 30;
    int marginX = 20;
    int marginY = 5;
    int initialX = marginX; // topleft
    int initialY = 120;
    int nameX;
    int creatorX = width - marginX; // topright!
    
    float yOffset = initialY + (i * textSize);
    float selectionYOffset = initialY + (selectedLanguage * textSize) - 2;
    
    float selectionYMargin = textDescent() / 3;
    
    textSize(textSize - (textSize  / 5));
    textAlign(LEFT, TOP);
    
    String id = "[" + str(i) + "]";
    int maxIDWidth = PApplet.parseInt(textWidth("[99]"));
    nameX = initialX + maxIDWidth + marginX;
    
    text(id, initialX, yOffset);
    
    text(l.getString("language"), nameX, yOffset);
    
    fill(THEME_FOREGROUND_COL);
    textAlign(RIGHT, TOP);
    text(localisation.getString("UI_SCENE_LANGUAGES_CREATOR_PRETEXT") + l.getString("creator"), creatorX, yOffset);
    
    fill(0, 0, 0, 0);
    stroke(THEME_HIGHLIGHT_COL);
    strokeWeight(1.5f);
    rect(initialX - (marginX/2), selectionYOffset - selectionYMargin, creatorX , textSize - selectionYMargin);
        
  }   

  if(introMenuNext.handle()){
    scene = SCENE_INTRO_TUTORIAL; 
  }
  
}
final String PROJECT_LIST_FILE_FILEPATH = "projects/list.json";


public void projectSelector(){
  
  if(projectMenuBack.handle()){
    scene = SCENE_HOME; 
  }
  
  fill(THEME_FOREGROUND_COL);
  strokeWeight(0);
      
  textSize(40);
  textAlign(CENTER, TOP);
  text(localisation.getString("UI_SCENE_PROJECT_SELECT"), width/2, 10);

  textSize(18);
  text(localisation.getString("UI_SCENE_PROJECT_SELECT_SUB1"), width/2, 60);
  



}
final String THEME_FILE_FILEPATH = "internal/themes.json";
final int LATEST_THEME_FILE_VERSION = 0;

JSONArray themes;

int THEME_BACKGROUND_COL, THEME_FOREGROUND_COL, THEME_HIGHLIGHT_COL, THEME_ERROR_MAJOR_COL, THEME_UNAVAILABLE_COL;
PFont THEME_FONT;

int selectedTheme = 0;

public boolean themeInit(){
 
  themes = loadJSONArray(THEME_FILE_FILEPATH);
  
  if(themes == null){
    
    println("Unable to load theme file");
    return false;
    
  }
  
  loadTheme(selectedTheme);
  
  return true;
  
}

public void themeSelector(){
  
  if(themeMenuBack.handle()){
   
    scene = SCENE_SETTINGS;
    
  }
  
  fill(THEME_FOREGROUND_COL);
  strokeWeight(0);
      
  textSize(40);
  textAlign(CENTER, TOP);
  text(localisation.getString("UI_SCENE_THEMES"), width/2, 10);

  textSize(18);
  text(localisation.getString("UI_SCENE_THEMES_SUB1"), width/2, 60);
  
  fill(THEME_ERROR_MAJOR_COL);
  textSize(18);
  text(localisation.getString("UI_SCENE_THEMES_SUB2"), width/2, 80);
  
  for(int i = 0; i < themes.size(); i++){

    fill(THEME_FOREGROUND_COL);
    strokeWeight(0);
    
    JSONObject t = themes.getJSONObject(i);
  
    // [id] name    creator
    int textSize = 30;
    int marginX = 20;
    int marginY = 5;
    int initialX = marginX; // topleft
    int initialY = 120;
    int nameX;
    int creatorX = width - marginX; // topright!
    
    float yOffset = initialY + (i * textSize);
    float selectionYOffset = initialY + (selectedTheme * textSize) - 2;
    
    float selectionYMargin = textDescent() / 3;
    
    textSize(textSize - (textSize  / 5));
    textAlign(LEFT, TOP);
    
    String id = "[" + str(i) + "]";
    int maxIDWidth = PApplet.parseInt(textWidth("[99]"));
    nameX = initialX + maxIDWidth + marginX;
    
    text(id, initialX, yOffset);
    
    if(t.getInt("version") < LATEST_THEME_FILE_VERSION){
      
      fill(THEME_ERROR_MAJOR_COL);
      
    }
    text(t.getString("themeName"), nameX, yOffset);
    
    fill(THEME_FOREGROUND_COL);
    textAlign(RIGHT, TOP);
    text(localisation.getString("UI_SCENE_THEMES_CREATOR_PRETEXT") + t.getString("creator"), creatorX, yOffset);
    
    fill(0, 0, 0, 0);
    stroke(THEME_HIGHLIGHT_COL);
    strokeWeight(1.5f);
    rect(initialX - (marginX/2), selectionYOffset - selectionYMargin, creatorX , textSize - selectionYMargin);
    
  } 
    
}


public void loadTheme(int selection){
 
  JSONObject theme = themes.getJSONObject(selection);
  
  if(theme.getInt("version") < LATEST_THEME_FILE_VERSION){
    
    return;
    
  }
  
  THEME_BACKGROUND_COL  = color(theme.getInt("backgroundColorR"), theme.getInt("backgroundColorG"), theme.getInt("backgroundColorB"));
  THEME_FOREGROUND_COL  = color(theme.getInt("foregroundColorR"), theme.getInt("foregroundColorG"), theme.getInt("foregroundColorB"));
  THEME_HIGHLIGHT_COL   = color(theme.getInt("highlightColorR"), theme.getInt("highlightColorG"), theme.getInt("highlightColorB"));
  THEME_ERROR_MAJOR_COL = color(theme.getInt("majorErrorColorR"), theme.getInt("majorErrorColorG"), theme.getInt("majorErrorColorB"));
  THEME_UNAVAILABLE_COL = color(theme.getInt("unavailableColorR"), theme.getInt("unavailableColorG"), theme.getInt("unavailableColorB"));
  THEME_FONT = createFont(theme.getString("fontFile"), 100);
  textFont(THEME_FONT);

  loadUIElements(); // Reload UI elements to apply new colors
    
  saveDataToSave();
    
}

public void handleThemeIncrement(){
  
  selectedTheme = (selectedTheme + themes.size() + 1) % themes.size();
  loadTheme(selectedTheme);
  
}
public void handleThemeDecrement(){

  selectedTheme = (selectedTheme + themes.size() - 1) % themes.size();
  loadTheme(selectedTheme);
  
}
final int UI_BUTTON_CENTER = -1;

class UIButton{
   
  int buttonWidth;
  int buttonHeight;
  int buttonX;
  int buttonY;
  float buttonRadius;
  int buttonStrokeWeight;
  int buttonFillCol;
  int buttonFillHighlightCol;
  int buttonStrokeCol;
  int buttonStrokeHighlightCol;
  String buttonText;
  int buttonTextSize;
  int buttonTextCol;
  int buttonTextHighlightCol;
  
  UIButton(int w, int h, int x, int y, int weight, int f, int fh, int s, int sh, int c, int ch, String t){
   
    buttonWidth = w;
    buttonHeight = h;
    buttonY = y;
    
    if(x == UI_BUTTON_CENTER){
     
      buttonX = (width/2) - (buttonWidth/2);
      
    }
    else{
      
      buttonX = x;
    
    }
    
    buttonRadius = buttonHeight - (buttonHeight/1.3f);
    buttonStrokeWeight = weight;
    buttonFillCol = f;
    buttonFillHighlightCol = fh;
    buttonStrokeCol = s;
    buttonStrokeHighlightCol = sh;
    buttonTextCol = c;
    buttonTextHighlightCol = ch;
    buttonText = t;
    buttonTextSize = buttonHeight - 10;
    
  }
  
  public boolean handle(){
    
    if(isMouseReleased){
           
      if(isMouseOver(buttonX, buttonY, buttonX + buttonWidth, buttonY + buttonHeight) && isXYOver(buttonX, buttonY, buttonX + buttonWidth, buttonY + buttonHeight, mouseReleasedX, mouseReleasedY)){
       
        fill(buttonFillHighlightCol);
        stroke(buttonStrokeHighlightCol);
        strokeWeight(buttonStrokeWeight);
        rect(buttonX, buttonY, buttonWidth, buttonHeight, buttonRadius);
        textAlign(CENTER, CENTER);
        textSize(buttonTextSize);
        fill(buttonTextHighlightCol);
        text(buttonText, buttonX + (buttonWidth/2), buttonY + (buttonHeight/2));
        isMouseReleased = false;
        return true;
   
      }
      
    }
    
    fill(buttonFillCol);
    stroke(buttonStrokeCol);
    strokeWeight(buttonStrokeWeight);
    rect(buttonX, buttonY, buttonWidth, buttonHeight, buttonRadius);
    textAlign(CENTER, CENTER);
    textSize(buttonTextSize);
    fill(buttonTextCol);
    text(buttonText, buttonX + (buttonWidth/2), buttonY + (buttonHeight/2));
    return false;     
    
    
  }
  
  public boolean isMouseOver(int x1, int y1, int x2, int y2){
    
    return (mouseX > x1) && (mouseX < x2) && (mouseY > y1) && (mouseY < y2);
  
  }
  
  public boolean isXYOver(int x1, int y1, int x2, int y2, int pX, int pY){
    
    return (pX > x1) && (pX < x2) && (pY > y1) && (pY < y2);
  
  }
  
}


  public void settings() { size(900, 500); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "ConsoleEmulator" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
